### ISSUE TITLE
انتخاب پروتکل های موجود

### ISSUE THREAD

**Issue by rbsdotnet** [erfjab/holderbot#1]
درود
من تست کردم و جواب داد
یه موردی هست اینکه من پروتکل vless و trojan دارم اما فقط پروتکل vless رو برای کاربر اضافه میکنه
در صورتیکه باید هر 2 پروتکل رو انتخاب کنه
امکانش ویرایش بهتر هست توی همین نسخه باشه
این مرود اصلاح بشه عالی و اینکه اگر بشه این ویژگی رو در خود پنل مرزبان باشه خیلی بهتره

**Comment by erfjab** [comment]
با سلام ، وقتتون بخیر عزیز
بله درست میفرمایید ، سورس اصلاح شد. الان از همه ی پروتوکل های موجود در سرور پیشتیبانی میکنه. ✅
در مورد امکان ویرایش ، اگر فرصتی کنم در آینده آپدیت های به درد بخوری خواهیم داشت. موفق باشید.
