### ISSUE TITLE
پیشنهاد(اضافه شدن حجم کل)

### ISSUE THREAD

**Issue by jsmohssen** [erfjab/holderbot#10]
این بخش یرای کاربر اکر آیتم حجم کل هم اضاف بشه می تونه کاربردی تر باشه ممنون![image](https://github.com/erfjab/holderbot/assets/118536893/058c7445-8b3f-4be8-956f-2c0c54f1c7bf)

**Comment by erfjab** [comment]
سلام وقت بخیر
ممنون از پیشنهاد تون ، حتما بررسی و نظرسنجی و اضافه میشود.
