### ISSUE TITLE
(باگ)ساخت یوزر

### ISSUE THREAD

**Issue by jsmohssen** [erfjab/holderbot#11]
باسلام هر چند شاید این مشکل ارتباطی با holderbot نداشته باشه اما فکر میکنم بی تاثیر نباشه..
هنگامی که در holderbot یوزری ساخته میشه، مشکلی در بات اصلی مرزبان بخش Users ها ایجاد میشه در واقع این کزینه غیر فعال میشه فکر میکنم تداخلی بوجود میاد که این اتفاق میفته، اما وقتی یوزر ساخته شده رو پاک میکنم مجددن بات شروع به کار میکنه..![image](https://github.com/erfjab/holderbot/assets/118536893/c7216203-0af8-4c77-a2af-ba46d3e4cb6a)

**Comment by erfjab** [comment]
سلام وقت بخیر، جهت اطمینان تست کردم و مشکلی دریافت نکردم، بازم کدهارو بررسی و بهینه میکنیم. ممنون از اطلاع رسانی تون

**Comment by jsmohssen** [comment]
ممنونم من چندین بار تست کردم این مشکل بود🙏🏻

**Comment by erfjab** [comment]
عزیز تست کردیم ، به خاطر اضافه نشدن status on_hold به بات اصلی مرزبان، این مشکل ممکنه پیش بیاد. ضمنا شما می‌توانید لیست کاربران با دستور /users دریافت کنید.

**Comment by jsmohssen** [comment]
> عزیز تست کردیم ، به خاطر اضافه نشدن status on_hold به بات اصلی مرزبان، این مشکل ممکنه پیش بیاد. ضمنا شما می‌توانید لیست کاربران با دستور /users دریافت کنید. 

بله در on_hold همه چیز عالی و بی عیبو نقص هست، مدیرت کانفیگ ها در بات اصلی برای اینجانب صرفا بخاطر امکان دیلیت کردن یوزرها، والا اکه این کزینه در on_hold موجود بود با یه دستور بات اصلی مرزبان رو حذف میکردیم

**Comment by erfjab** [comment]
چشم آقا محسن ،برای شما این آپدیت نسخه‌ی 4 هولدربات امکان حذف کانفیگ هم اضافه میکنیم.
