### ISSUE TITLE
دستور آپدیت

### ISSUE THREAD

**Issue by jsmohssen** [erfjab/holderbot#13]
لطفا بفرماید هنگامی که خواستیم بات رو آپدیت کنیم چه دستوری باید بزنیم؟

**Comment by erfjab** [comment]
سلام وقت بخیر، از دستورات نصب هم برای آپدیت میتوانید استفاده کنید.

**Comment by jsmohssen** [comment]
یعنی مراحل نصب رو از اول ران کنیم سه دستور و اطلاعت پنل؟

**Comment by erfjab** [comment]
بله عزیز
