### ISSUE TITLE
پیشنهاد (دستور آپدیت)

### ISSUE THREAD

**Issue by jsmohssen** [erfjab/holderbot#14]
با توجه به اینکه فرایند بروزرسانی فعلی بات ممکن است در زمان های متفاوت کمی دشوار باشد، لطفا در صورت صلاحدید یا دستور رو در قالب یک اسکریپت پیاده سازی بفرمایید ویا در قالب دستور /update و یا اینکه به منو های بات دستور آپدیت اضافه بشه که این مورد در صورت ممکن خیلی خیلی کار رو برای کاربر راحت و راحتر میکنه که می تونه خیلی جذاب و مفید باشه،بازم ممنون بابت این بات کاربردی و مفید

**Comment by erfjab** [comment]
سلام وقت بخیر، ممنون از پیشنهادتون، حتما بررسی و نظرسنجی و اضافه میکنم.
