### ISSUE TITLE
گزارش کاربر 

### ISSUE THREAD

**Issue by vahidyeganeh1373** [erfjab/holderbot#16]
متن گزارشی که از یک کاربر بما میده عین یه متن پشت سرهم میده و خواندنش یخورده سخته 

اینطوری : 
نام کاربری : KinG (فعال)حجم مانده : 49.81 گیگروز مانده : 29 روزتاریخ انقضاء : 1402/12/14آخرین تایم آنلاینی : 13 ثانیه پیشآخرین آپدیت ساب : 59 دقیقه پیش

اگه امکانش هست هر مشخصه ای تو یه خط باشه که خوانا تر باشه و ترجیحا با یه آیکونی چیزی

**Comment by erfjab** [comment]
سلام وقت بخیر ، از html ها استفاده شده بود ولی تغییر داده شد ، الان درسته ، لطفا آپدیت کنید.
