### ISSUE TITLE
قابلیت تعین نوع کانفینگ

### ISSUE THREAD

**Issue by hayousef68** [erfjab/holderbot#2]
کاش می شد این گزینه هم اضافه کرد که چه کانفینگی ساخته بشه مثلا من الان پنلم هم vemess دارم هم veless ولی فقط یکیشو میدم مشتری ربات ولی از هر دوتاش میسازه بخوام هم ویرایش کنم شروعشو میزنه

**Comment by HoroshoVse** [comment]
Yes, and the ability to add vision to the vless config

**Comment by erfjab** [comment]
اضافه شد عزیز
Added dear.
