### ISSUE TITLE
پیشنهاد: حذف یوزرها

### ISSUE THREAD

**Issue by jsmohssen** [erfjab/holderbot#21]
اگر قابلیت حذف یوزرها هم اضاف بشه خیلی کاربردی تر خواهد بود..
بی صبرانه منتظر نسخه ی جدید هستیم میشه پرسید کی میاد؟
با تشکر🌷

**Comment by erfjab** [comment]
سلام وقت بخیر
با اجازه‌تون این اپشن رو برای آپدیت بعد نسخه‌ی 4 واگذار کنیم، با امکانات دیگر برای یوزرها.

**Comment by erfjab** [comment]
در حال کار بر روی نسخه‌ی 4 هستیم، تلاش می‌کنیم هرچه زودتر آماده بشود ولی بعد از 100 ستارگی ریلیز می‌شود.
