### ISSUE TITLE
فعال کردن اینباند مدنظر برای همه کاربران پنل

### ISSUE THREAD

**Issue by zeroarvintwo** [erfjab/holderbot#22]
فرض کنید برای همه کاربرها vless فعاله 
و ما میخوایم برای همه یوزر ها vmess رو هم فعال کنیم 
این یکم زمان بر میشه
خیلی خوب میشه اگر داخل ربات انجام بشه

**Comment by erfjab** [comment]
سلام وقت بخیر
این امکان در حال حاضر بات اصلی مرزبان دارد. میتوانید ازش استفاده کنید  بهتره ما تمرکزمون رو، روی قابلیت های غیرتکراری بزاریم. ممنون از پیشنهادتون
