### ISSUE TITLE
خطای i can't check inbounds !

### ISSUE THREAD

**Issue by firegoood** [erfjab/holderbot#23]
سلام.
من یک بار دستور ساخت رو زدم کاربر ساخت.به بعد همش این پیام را میدهد.چند باز هم دوباره نصب کردم.ممنون میشم راهنمایی کنید
❌ i can't check inbounds !
{"detail":"Could not validate credentials"}

**Comment by erfjab** [comment]
سلام وقت بخیر، از آخرین نسخه‌ی هولدربات استفاده کنید مشکل تون حل میشه، جهت آپدیت دستورات نصب رو از اول طی کنید. بازم مشکلی بود در این تایپک اعلام کنید.

**Comment by firegoood** [comment]
نسخه رو تازه امروز دوباره هم نصب کردم
ورژن 3.2.1
بازم حل نشد

**Comment by erfjab** [comment]
کانفیگ اولیه رو هم نمیسازه؟ دسترسی ادمین اصلی و دامین با پورت میدید بهش؟
sub.domain.com:port

**Comment by firegoood** [comment]
خیر.
با ادمین اصلی و یک ادمین دیگه هم ساختم.بکاپ مرزبانو روی یک سرور دیگه هم بردم و از نو رو اون سرور نصب کردم بازم همون ارور رو میده.
دامین و پورت رو هم درست میدم

**Comment by erfjab** [comment]
اسکرین شات خطا رو بفرستید لطفا

**Comment by firegoood** [comment]
![Uploading IMG_20240208_011548_060.jpg…]()

**Comment by firegoood** [comment]
عکس ارور
[https://ibb.co/PTMHMwf](url)

**Comment by erfjab** [comment]
عکس نیاورد، از تلگرام باهام در ارتباط باشید.
@Erfjab
