### ISSUE TITLE
پیشنهاد :  اضفه کردن قابلیت بک آپ به ربات

### ISSUE THREAD

**Issue by reza4fprm** [erfjab/holderbot#24]
سلام وقت بخیر، با تشکر از وقتی که برای توسعه این اسکریپت میزارید.
در حال حاضر ربات شما و ربات های دیگری برای بک آپ نصب کردیم . اگر قابلیت بک اپ از پنل مرزبان رو اضافه کنید خیلی خوب میشه.

**Comment by erfjab** [comment]
سلام وقت بخیر، ممنونم
در برنامه هامون هست ولی بعد از نسخه‌ی 4 اضافه خواهد شد.
