### ISSUE TITLE
اضافه شدن قابلیت لاگ چنل

### ISSUE THREAD

**Issue by Meytiz** [erfjab/holderbot#25]
سلام خسته نباشی.
بات خود مرزبان قابلیت لاگ داره که وصل میشه به چنل و تغییرات رو میبینی اگه اضافه کنی و بهترش کنی خیلی خوب میشه

**Comment by erfjab** [comment]
سلام وقت بخیر، ممنونم
چشم حتما در برنامه هامون قرار میدیم.

**Comment by erfjab** [comment]
برای این موضوع نیاز به نصب بات رو سرور مستر و دسترسی به لاگ هاست که پروسه‌ی زمان بر و سختیه که در حال حاضر خود بات اصلی مرزبان داره.
