### ISSUE TITLE
اضافه کردن قابلیت..on_hold به اکانت تموم شده

### ISSUE THREAD

**Issue by hayousef68** [erfjab/holderbot#26]
سلام 

کاش میشد اینم اضافه کنین که مثلا اکانتی که تموم شده دوباره اینطوری تنظیم کنیم بعد از عوض کردن لینک ساب دوباره با قابلیت on_hold شارژ کنیم بدیم دست مشتری. نمیدونم تونستم منظورمو برسونم یا نه .اینطوری خیلی خوب میشه و از ساخت دوباره یوزرهای زیاد جلوگیری میشه پنل هم سنگین نمیشه

**Comment by erfjab** [comment]
سلام وقت بخیر، چشم حتما در برنامه هامون قرار میدیم
