### ISSUE TITLE
نشون ندادن گزینه های بات

### ISSUE THREAD

**Issue by wrath1300** [erfjab/holderbot#28]
سلام
یه مشکلی من دارم دستورات اجرا کردم وصل شد به پنل ولی هیچ دکمه ای توی ربات برام نشون نمیده. کار اضافه تری باید انجام بدم ندادم؟
![Scذbot7](https://github.com/erfjab/holderbot/assets/144748973/be8dc8a1-7def-4a00-b41d-736830bd9e30)

**Comment by jsmohssen** [comment]
دستورات رو باید تایپ کنی فعلا اما در نسخه ۴ همه چیز بهینه شده، یا اینکه در ربات بات فادر @BotFather دستورات رو اضاف کنی به بات که نیازی به تایپ نباشه..
تمامی دستورات در کانال تلگرامی holderbot به همراه آموزش موجود است..
دستور زیر برای نمایش کاربران
/users
برای اطلاعات بیشتر و جامع تر لطفا عضو کانال باشید در جریان جزییات دقیقتر قرار بگیرد

https://t.me/ErfjabHolderbot

**Comment by jsmohssen** [comment]
> سلام
> 
> یه مشکلی من دارم دستورات اجرا کردم وصل شد به پنل ولی هیچ دکمه ای توی ربات برام نشون نمیده. کار اضافه تری باید انجام بدم ندادم؟
> 
> ![Scذbot7](https://github.com/erfjab/holderbot/assets/144748973/be8dc8a1-7def-4a00-b41d-736830bd9e30)
> 
> 

دستورات رو باید تایپ کنی فعلا اما در نسخه ۴ همه چیز بهینه شده، یا اینکه در ربات بات فادر @Botfather دستورات رو اضاف کنی به بات که نیازی به تایپ نباشه..
تمامی دستورات در کانال تلگرامی holderbot به همراه آموزش موجود است..
دستور زیر برای نمایش کاربران
/users
برای اطلاعات بیشتر و جامع تر لطفا عضو کانال باشید تا در جریان جزییات دقیقتر قرار بگیرد

https://t.me/ErfjabHolderbot
