### ISSUE TITLE
ارور ssl

### ISSUE THREAD

**Issue by mohamadaz** [erfjab/holderbot#30]
همه کار هارو درست انجام میدم اما موقع ساختن اکانت ارور ssl دارم

httpsconnectionpool(host='ادرس دامنه', port=443): max retries exceeded with url: /api/admin/token (caused by sslerror(ssleoferror(8, 'eof occurred in violation of protocol (_ssl.c:1131)')))

**Comment by erfjab** [comment]
سلام وقت بخیر عزیز
دامنه تون رو باید طبق الگوی زیر وارد کنید.
sub.domain.com:port

**Comment by mohamadaz** [comment]
پورتم ۴۴۳ هست و طبق همین الگو وارد کردم

**Comment by erfjab** [comment]
شاید دامنه‌ی ساب رو با دامنه‌ی پنل اشتباه وارد کردید.
بات اوکیه، بازم یکی دو امتحان کنید.

**Comment by mohamadaz** [comment]
من ساب لینکم فوروارد شده 
این دفعه ارور مربوط به inbound tag دریافت کردم

**Comment by erfjab** [comment]
خب نمیتونه اینباند هارو چک کنه، لینک‌تون مشکل داره عزیز

**Comment by mohamadaz** [comment]
راهنمایی میکنید دقیقا کدوم لینک رو باید بزارم؟

**Comment by erfjab** [comment]
از طریق تلگرام باهام در ارتباط باشید
@Erfjab
