### ISSUE TITLE
نصب روی سرور ایران

### ISSUE THREAD

**Issue by hayousef68** [erfjab/holderbot#31]
سلام مهندس من پنلم روی سرور ایران هست نمیتونه به سرور تلگرام وصل بشه میشه راهنمایی کنین خیلی واجبه

**Comment by erfjab** [comment]
سلام وقت بخیر، نیازی نیست حتما رو سرور پنل‌تون نصب کنید، میتونید سرور جدایی تهیه کنید.

**Comment by hayousef68** [comment]
امکانش هست بشه رو سرور ایران اجرا کرد ؟؟

**Comment by erfjab** [comment]
تلگرام داخل ایران فیلتره عزیز، نمیشه. مگر اینکه خودتون رو بات پروکسی اعمال کنید که ممکنه برای سرورتون مشکل ساز باشه.
