### ISSUE TITLE
ادغام با ربات مرزبان

### ISSUE THREAD

**Issue by phoenix-marzban** [erfjab/holderbot#32]
سلام دوست عزیز بابت رباتی که طراحی کردی عالیه لذا وقتی ربات شمارو با ربات مرزبان فعال میکنم قسمت users ربات مرزبان از کار میافته نمیدونم علتش چیه یا شاید از من باشه لطفا بررسی کنید..

**Comment by erfjab** [comment]
سلام وقت بخیر، ممنون از لطف‌تون.
به خاطر اینکه Users مرزبان on_hold رو در حال حاضر ساپورت نمیکنه.
