### ISSUE TITLE
مشکل

### ISSUE THREAD

**Issue by jsmohssen** [erfjab/holderbot#34]
با سلام خدمت عرفان عزیز
یه چند مورد هست که در نسخه ی قبلی بتا هم بود نسخه ی جدید هم کما کما کن وجود داره..
بخش سرچ بهینه سازی انجام شده اما احساس من بر این هست که بات اینبار برای پیدا کردن خیلی دقیقتر باید کلامت را برایش ادا کرد  درصورتی که این موضوع برای سرچ در بخش شروع شده بات یعنی به جز قسمت سرچ، خیلی دقیق تر عمل می کند،و اینکه در بخش سرچ بات به کلامت بزرگ و کوچک حساس نیست اما در بخش جدا از سرچ حساس است مثلا اگر کاربری با نام Admin وجود دارد حتما باید با A بزرگ جستجو شروع شود در غیر اینصورت کاربر admin را پیدا می کند و اگر کپی کنم بخایم مشخصات یوزر رو ببینیم نمیشه چون کاربر اصلی با حرف بزرگ ساخته شده.
مورد بعدی در  تمپلت ها گزینه حذف وجود ندارد این مورد هم اگر ممکنه اضافه بشه تا در صورت اشتباه یه عدم نیاز بشه حذفش کرد![image](https://github.com/erfjab/holderbot/assets/118536893/b292864a-7ffd-4dc1-a326-fc6ee86c8af5)

**Comment by erfjab** [comment]
سلام وقت بخیر، بررسی میکنیم، ممنون از شما❤️
