### ISSUE TITLE
پرداخت دونیت

### ISSUE THREAD

**Issue by hossein2** [erfjab/holderbot#35]
سلام مهندس والا دیگه نمیدونستم کجا باید پیغاام بذارم 
دونیت پرداخت کردیم طور لایسنس میشه ؟؟
ایا سورس کامل ربات در اختیار ما میذارید چطوریه ؟؟

**Comment by erfjab** [comment]
سلام وقت بخیر، به صورت سورس کامل دریافت خواهی کرد عزیز.

**Comment by hossein2** [comment]
الان پرداخت کردم ایدی تلگرام دارید بفرشتید

**Comment by erfjab** [comment]
مرسی ممنونم ،عزیز تو چنلم اعلام کردیم، تا آخر هفته صبر میکنیم، اگر به مبلغ قابل توجهی برسه پابلیک میشه، در غیراینصورت مختص افراد محدودی (و افرادی که دونیت کردن) میشه، یعنی تا آخر هفته باید صبر کنید. @erfjab جهت ارتباط هم با آیدی در خدمتم.
