### ISSUE TITLE
تاخیر در ارسال لاگ یوزر های آنلاین

### ISSUE THREAD

**Issue by Choobin-Faraaseman** [erfjab/holderbot#36]
درود
اول از همه تشکر بابت بات👌🙏
ارسال لاگ یوزر های آنلاین اخیر; با تاخیر انجام میشه.
بعضی وقتا همون لحظه میرفرسته بعضی وقتا با 5 دقیقه تاخیر میفرسته.
حالا نمیدونم مشکل از سمت منه یا ربات
سروری که بات روش نصبه پرومو آیزاست
دیتابیس پنل sqllite

**Comment by erfjab** [comment]
سلام وقت بخیر، ممنون از لطف‌تون🙏
منظورتون از پرومو آیزاست رو متوجه نشدم.
