### ISSUE TITLE
 ۴ مشکل در ساخت یوزر گروهی در آپدیت 

### ISSUE THREAD

**Issue by hayousef68** [erfjab/holderbot#37]
سلام. من تو آپدیت ۴ نمیتونم یوزر گروهی با اسم و کد دلخواه مثل وژن ۳ بسازم قبلا یه دستور میزدیم /cr SIGMA@p. 45 10 30 30 راحت اینطوری ۱۰ تا درست میکرد ولی الان نه

**Comment by erfjab** [comment]
سلام وقت بخیر، این دستور در نسخه‌ی 4 هولدربات فعلا حذف شده به جاش میتونید از create user استفاده کنید، با تمپلیت یا بدون تمپلیت، میدونید به تعداد دلخواه بسازید.

**Comment by hayousef68** [comment]
> سلام وقت بخیر، این دستور در نسخه‌ی 4 هولدربات فعلا حذف شده به جاش میتونید از create user استفاده کنید، با تمپلیت یا بدون تمپلیت، میدونید به تعداد دلخواه بسازید.

یعنی یوزر گروهی دیگه نمیشه ساخت؟؟؟

**Comment by erfjab** [comment]
عزیز create user نسخه‌ی 4 هولدربات رو تا حالا تست کردید؟ 😅 میشه ساخت. خیلی راحت تر و بهتر

**Comment by hayousef68** [comment]
> عزیز create user نسخه‌ی 4 هولدربات رو تا حالا تست کردید؟ 😅 میشه ساخت. خیلی راحت تر و بهتر

تست کردم داداش تکی میسازه اصلا سوالی بر اینکه چند تا یوزر بسازم و از چه کدی شروع بشه نمیاد فقط اسم و حجم و روز میاد

**Comment by erfjab** [comment]
بله شما کاملا درست می‌فرمایید، تو create user ما به تمپلیت ها  ساخت گروهی یوزر اضافه کردیم ولی به Manual اضافه نکردیم یادمون رفته، حتما بهش رسیدگی می‌کنیم. ممنون از شما🙏

**Comment by hayousef68** [comment]
> بله شما کاملا درست می‌فرمایید، تو create user ما به تمپلیت ها ساخت گروهی یوزر اضافه کردیم ولی به Manual اضافه نکردیم یادمون رفته، حتما بهش رسیدگی می‌کنیم. ممنون از شما🙏
ممنون بابت پیگیریتون.قسمت تمپلت ها هم که میایم یوزر بسازیم اسم میپرسه که با چه اسمی بسازیم مثلا من اسم رو میزنم @ میزنم شماره رو میزنم بدونم از کدوم سرور هست با چه شماره این مثلا به این صورت SIGMA@p.65 ربات @ رو حدف میکنه و اسم یوزر رو بدون @ میسازه به این صورت SIGMAp.65

**Comment by hayousef68** [comment]
> بله شما کاملا درست می‌فرمایید، تو create user ما به تمپلیت ها ساخت گروهی یوزر اضافه کردیم ولی به Manual اضافه نکردیم یادمون رفته، حتما بهش رسیدگی می‌کنیم. ممنون از شما🙏

ممنون بابت پیگیریتون.قسمت تمپلت ها هم که میایم یوزر بسازیم اسم میپرسه که با چه اسمی بسازیم مثلا من اسم رو میزنم @ میزنم شماره رو میزنم بدونم از کدوم سرور هست با چه شماره این مثلا به این صورت SIGMA@p.65 ربات @ رو حدف میکنه و اسم یوزر رو بدون @ میسازه به این صورت SIGMAp.65

**Comment by erfjab** [comment]
چشم حتما. از طریق تلگرام باهام در ارتباط بمونید : @erfjab

**Comment by hayousef68** [comment]
> چشم حتما. از طریق تلگرام باهام در ارتباط بمونید : @erfjab

چشم.ممنون
