### ISSUE TITLE
کار نکردن ربات بعد از ریبوت 

### ISSUE THREAD

**Issue by aliakbar123as** [erfjab/holderbot#38]
لطفاً یک کرون ایجاد کنید که بعد از ریبوت سرور ربات مجدد استارت بشه

**Comment by vahidyeganeh1373** [comment]
توی ورژن 4.4.2 نوشته بودید که مشکلش حل شده و کرون جاب تعریف کردید براش
دیشب سرور رو ریبوت کردم و دیدم کار نکرد
بعد دیدم تو قسمت کرون جاب این متن رو نوشته فکر کنم بخاطر اون فاصله بعد از bash هست اگه بخاطر همینه ویرایشش کنید
@reboot sleep 20 && /bin/bash /holderbot/restart.sh
