### ISSUE TITLE
نیومدن نوتیف هنگام تغییرات

### ISSUE THREAD

**Issue by seenpeh** [erfjab/holderbot#39]
سلام، دستت درد نکنه بابت این پروژه
منتهی تا جایی که من می‌دونم امکاناتی مثل نوتیف هنگام ایجاد، تغییر، حذف کاربرا یا بکاپ گیری از بات توی فیچراش نیست درسته؟

اگه مایل به همکاری بودی می‌تونی به تلگرامم پیام بدی

**Comment by erfjab** [comment]
سلام وقتتون بخیر، ممنون از لطف‌تون و با تشکر از پینشهاد همکاری‌تون🙏 هولدربات هدفش ارائه ی قابلیت های خاص و غیرتکراری میباشد که نامبرده هارو بات دیفالت دارد. هولدربات فعلا در فاز اول تلاشش بر اینه که با api ها عملیات مدنظرش رو انجام بده. در فاز دوم تلاش میکنه کارشو با دیتابیس انجام بده ولی فعلا اون مراحل مونده عزیز. نیازیم نداریم ذاتا. اگر میتوانید همکاری کنید احتیاج به بهینه سازی بخش Search داریم، بخش regax template name ها نیاز به اجازه ی وارد کردن Custom name داریم و... اینا در برنامه های هدیفای موموده و اگهدتونستید کمکمون بکنید سپاس‌گزار میشیم. ممنون از شما
