### ISSUE TITLE
لیست کردن یوزر بر اساس روز های باقیمانده

### ISSUE THREAD

**Issue by MHMahdian** [erfjab/holderbot#40]
سلام

ممنون از زحمات شما بابت رباتی که ساختید یه چیزی که در بین ربات های مرزبان وجود نداره اینه که یوزر های در حال انقضا یا در حال تموم شدن حجم لیست کنه برای مثال ربات بیاد لیست یوزر هارو جوری بچینه که به ترتیب تموم شدن زمان باشن و یا تموم شدن حجم لطفاً این رو اضافه کنید 

باز هم ممنون از شما

**Comment by erfjab** [comment]
سلام وقت بخیر، ممنونم لطف دارید 🙏
این ایده توسط چند از نفر دوستان مطرح شده و حتما در لیست توسعه میباشد. خیالتون راحت.
