### ISSUE TITLE
راهنمایی

### ISSUE THREAD

**Issue by maaghaei** [erfjab/holderbot#41]
درود وقتتون بخیر این ربات درواقع میاد ربات خود مرزبان رو قابلیت هاش رو اضافه میکنه یا اینکه یه ربات کاملا جدا هستش؟
روی هاست یا سرور جدا هم میشه نصبش کرد یا روی همون سرور باید نصب بشه؟
![Screenshot_20240307_052310](https://github.com/erfjab/holderbot/assets/154073284/a5f33aec-c687-4b3d-881d-5a16aa267210)
توی این عکس باید این دستورات رو توی سرور نود بزنیم یا سرور اصلی؟

**Comment by erfjab** [comment]
سلام وقت بخیر
هولدربات. بات مستقل مدیریت پنل مرزبان میباشد که قابلیت‌های جدید و خاصی در جهت راحت‌تر و سریع‌تر کردن مدیریت پنل ارائه می‌دهد. همیشه هم در حال آپدیت و توسعه می باشد.
نصب بر روی سرور ابونتو اوکیه مستر یا جدا فرقی نداره. اون دستورات هم بله بایذ داخل سرور نود بزنید ، پنل هم آپدیت کنید.

**Comment by maaghaei** [comment]
ممنون بابت راهنماییتون و بات خوبتون یک سوال دیگه هم داشتم کسی نتونست جوابم رو بده من هر سروری میگیرم سیستم عامل اوبونتو دبیان نمیتونم پنل مرزبان رو نصب کنم مشکل داره یکی از لایر هاش رو کامل نمیکنه اینم عکس ارور هست

![Screenshot_20240307_085535](https://github.com/erfjab/holderbot/assets/154073284/2f10a9a7-7667-49c7-9e2a-7ddc562923df)

ممنون میشم اگر میتونید راهنماییم کنید

**Comment by erfjab** [comment]
در این موضوع آگاهی ندارم، در گروه مرزبان منتشر کنید
