### ISSUE TITLE
محدودیت ترافیک به ادمین ها 

### ISSUE THREAD

**Issue by javaheri1989** [erfjab/holderbot#43]
آیا میشه چنین ویژگی اضافه کرد که ادمین 1 ترا ترافیک داشته باشه. یا ترافیکش رو ما براش شارژ کنیم

**Comment by erfjab** [comment]
سلام وقت بخیر، آره میشه حتی برای یکی دو تا از دوستان زدیم ولی واسه هولدربات نیست، چون این مورد اختصاصی هست. باید اختصاصی نوشته شود. امکان تعریف پیشوند، پسوند برای یوزرنیم ها، محدودیت حداقل/حداکثر تعداد اکانت، محدودیت حداقل/حداکثر حجم و زمان و ضمنا اینباند. تو برنامه نویسی محدودیت نداریم هر ایده ای داشته باشید میتوانیم اجرا کنیم.

**Comment by javaheri1989** [comment]
در این خصوص ممنون میشم هزینه هاشو محبت کنید

**Comment by erfjab** [comment]
والا اینجا جاش نیست ولی خلاصه بگم یه چیز حرفه ای، با پشتیبانی کامل ما، حدودا 5 4 تومن هزینه خواهد داشت. همه‌ی ایده‌ و درخواست‌هاتون راجب ادمین ها + نظرات خودمون اجرا خواهد شد.
