### ISSUE TITLE
زبان فارسی

### ISSUE THREAD

**Issue by mrlinux0open** [erfjab/holderbot#49]
سلام چرا زبان فارسی به ربات و گیت هاب اضافه نمیشه ؟

**Comment by erfjab** [comment]
سلام وقت بخیر ، برای ویکی گیت هاب یکی از دوستان دارن زحمت میکشن ، برای ربات هم منتظر آپدیت های بعدی بمانید.

**Comment by mrlinux0open** [comment]
بلی خیلی عالیه واقعا ممنون بابت زحماتی که می‌کشید
