### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bloodh73** [erfjab/holderbot#5]

**Comment by bloodh73** [comment]
سلام من بعد از نصب این ارور توی بات میگیرم

❌ ارور :
HTTPSConnectionPool(host='www.domain.site', port=443): Max retries exceeded with url: /api/admin/token (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by erfjab** [comment]
دامنه رو چجوری وارد کردید؟
sub.domain.com ?

**Comment by Multivpnlive** [comment]
سلام من ورژن ۲ رو دارم چطور باید اپدیت کنم ؟

**Comment by erfjab** [comment]
> سلام من ورژن ۲ رو دارم چطور باید اپدیت کنم ؟

طبق دستورات گیت هاب جلو برید آپدیت میشه

**Comment by bloodh73** [comment]
> دامنه رو چجوری وارد کردید؟ sub.domain.com 
Sub.domain.com

**Comment by erfjab** [comment]
> > دامنه رو چجوری وارد کردید؟ sub.domain.com
> 
> دامنه رو به این صورت وارد کردم Sub.domain.com

عزیز آپدیت ها انجام شد، هم داکیومنت هم کد، لطفا طبق داکیومنت دوباره بررسی کتید،اینجوری وارد کنید.
sub.domain.com:port
