### ISSUE TITLE
وضعیت کاربرها

### ISSUE THREAD

**Issue by Parsa-ict** [erfjab/holderbot#51]
خیلی خسته نباشین، تشکر بابت ربات خوبتون

یه درخواست داشتم که اگر امکانش هست، قابلیتی اضافه کنید که مثلا یک روز قبل یا همون روزی که ساب قراره تایمش تموم شه ربات به ما اطلاع بده
خلاصه یه چیزی تو این مایه‌ها، حالا با هر متودی که فک میکنین بهتره

**Comment by erfjab** [comment]
> خیلی خسته نباشین، تشکر بابت ربات خوبتون
> 
> یه درخواست داشتم که اگر امکانش هست، قابلیتی اضافه کنید که مثلا یک روز قبل یا همون روزی که ساب قراره تایمش تموم شه ربات به ما اطلاع بده
> خلاصه یه چیزی تو این مایه‌ها، حالا با هر متودی که فک میکنین بهتره

سلام وقت بخیر، لطف دارید ❤️
چشم. حتما در لیست قابلیت ها قرار میدیم.
