### ISSUE TITLE
مشکل ربات در نود و ادمین

### ISSUE THREAD

**Issue by yash1380** [erfjab/holderbot#54]
سلام من ربات رو مطابق آموزش نصب کردم ولی به مشکل خورده بخش نود و ادمین کار نمیکنه و بعد نصب ربات هم پیام زیر نشون میده
nohup: appending output to 'nohup.out'

**Comment by erfjab** [comment]
> سلام من ربات رو مطابق آموزش نصب کردم ولی به مشکل خورده بخش نود و ادمین کار نمیکنه و بعد نصب ربات هم پیام زیر نشون میده
> nohup: appending output to 'nohup.out'
> 

سلام وقت بخیر، اطلاعات رو به شکل درستی وارد نکردید حتما، دامنه رو با فرمت sub.domain.com:port وارد کنید و در هنگام وارد کردن موجودی ssl فقط از y یا n استفاده کنید، مجددا ران کنید اطلاع بدید

**Comment by yash1380** [comment]
دقیقا با sub.domain.com:port تظیم شده و y رو زدم چون ssl برام فعاله
البته تو سرور مرکزی نصب کردم و همچنین رو اون ربات دیگر که قابلیت بکاپ خودکار داره ac lover  نصبه

**Comment by yash1380** [comment]
مجدد هم امتحان کردم باز همونه

**Comment by erfjab** [comment]
> نصبه

به سرور مرکزی و بات های دیگر ربطی نداره، ادمین سودو وارد کردید ؟

**Comment by yash1380** [comment]
اره ادمین اصلی رو وارد کردم

**Comment by erfjab** [comment]
> اره ادمین اصلی رو وارد کردم

تمامی موارد ممکن رو بررسی کردیم، فقط ادمین و نود کار نمیکنه؟

**Comment by yash1380** [comment]
اره همه بخش ها کار میکنه تست کردم حتی یوز هم ساختم 
فقط نود و ادمین کار نمیکنه

**Comment by erfjab** [comment]
> اره همه بخش ها کار میکنه تست کردم حتی یوز هم ساختم 
> فقط نود و ادمین کار نمیکنه 

ادمین جدیدی برای بات بسازید، شاید اون ادمین سودو نیست، چون سودو نباشه نمیتونه به نود و ادمین دسترسی داشته باشه.

**Comment by yash1380** [comment]
marzban cli admin create --sudo
با این دستور بسازم درسته ؟

**Comment by erfjab** [comment]
> marzban cli admin create --sudo
> با این دستور بسازم درسته ؟

بله درسته

**Comment by yash1380** [comment]
با ادمین جدید هم کار نکرد

**Comment by yash1380** [comment]
```
HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //test.test.com:8443/api/nodes (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8358b9efb0>: Failed to resolve 'https' ([Errno -3] Temporary failure in name resolution)"))
Traceback (most recent call last):
  File "/holderbot/hold/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "/holderbot/hold/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
```
این یه نمونه ارور لاگ رباته قسمت نام دامنه رو خودم تغییر دادم

**Comment by erfjab** [comment]
> ```
> HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //test.test.com:8443/api/nodes (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8358b9efb0>: Failed to resolve 'https' ([Errno -3] Temporary failure in name resolution)"))
> Traceback (most recent call last):
>   File "/holderbot/hold/lib/python3.10/site-packages/urllib3/connection.py", line 198, in _new_conn
>     sock = connection.create_connection(
>   File "/holderbot/hold/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>   File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -3] Temporary failure in name resolution
> ```
> این یه نمونه ارور لاگ رباته قسمت نام دامنه رو خودم تغییر دادم

این ارور به خاطر ورودی اشتباه دامنه می‌باشد.

**Comment by yash1380** [comment]
خب من دامنه رو دقیقا اینجوری وارد  میکنم
test.exampel.ir:8443
اگه دامنه اشتباه باشه چرا بخش ایجاد کاربر از ربات یا بخش های دیگ کار میکنه

**Comment by erfjab** [comment]
> پورت خاصی باید آزاد باشه ؟ مثلا 80 یا 443 و..

نه ربطی به پورت نداره، من تا همچین مشکلی ندیدم، فقط توجیه اش این میتونه باشه که ادمین سودو نیست که اونم گفتید هست، در وقت خالی برام دسترسی تونستید بفرستید که چکش کنم. @Erfjab تلگرام

**Comment by erfjab** [comment]
> پورت خاصی باید آزاد باشه ؟ مثلا 80 یا 443 و..

اوکی شد عزیز
