### ISSUE TITLE
نحوه حذف برنامه

### ISSUE THREAD

**Issue by farshadl** [erfjab/holderbot#56]
چطور میتونم بات holderbot را روی سرورم unistall کنم؟

**Comment by soheylshorg** [comment]
دستور رو که دوبارع بزنی کامل پاک میشه چون به صورت کرونجابه

**Comment by farshadl** [comment]
یعنی من مجددا دستور نصب را که بزنم، برنامه حذف میشه؟
من مجدا دستور نصب را زدم و دوباره رفت توی مرحله وارد کردن nickname و .......!
روی سرور هم که SFTP زدم، محتویات فایل‌های بات هنوز موجوده و برنامه پاک نشده

**Comment by soheylshorg** [comment]
فایل های اولش ریمو میشه ودوباره خام میشه فعلن تنها راهشه تا بعدن براش اوکی کنن اون قسمتو

**Comment by erfjab** [comment]
بزودی اضافه میشه.
