### ISSUE TITLE
گسترش دادن بخش Notice

### ISSUE THREAD

**Issue by MHMahdian** [erfjab/holderbot#57]
ممنون از عرفان گل که زحمت این ربات رو کشیده 

دوتا ایده دارم که احتمالا قابل اجرا باشه ، اول اینکه وقتی یوزر لیمیت میشه به جای اینکه یک کانفینگ نشون بده حجم شما تمام شد یه کانفینگ رو به صورت جیسون ارسال کنه که توش فرگمنت باشه یعنی مثلا یک فرگمنت ایجاد کنم که جیسون اون فایل رو به ارسال کنه تا کاربر بیاد بهش وصل بشه و با مثلا سرعت کم( چون اکثر فرگمنت ها سرعت جالبی ندارند ) وارد تلگرام بشه و پیام بده که براش تمدید کنیم 

یه ایده دیگه اینکه توی کانفینگ های لینک اشتراک بتونیم علاوه بر کانفینگ هایی که یوزر خرید کرده چند تا کانفینگ دیگه ارسال بشه مثلا من قراره به تموم اعضا عیدی کانفینگ دو روزه بدم و می خوام برای تموم یوزر ها فعال بشه که اگه به اون کانفینگ وصل بشن اصلا از حجمشون کم نشه و رایگان براشون بیوفته یعنی اون کانفینگ از کل پنل جدا باشه ولی بیاد برای بوزر ها 

بخش Notice ام اگه بشه برای یوزر ها جدا بشه که مثلا برای یوزر های نماینده ها متن جدا براشون بره که عالی میشه

به امید موفقیت بیشتر شما ❤️❤️

**Comment by phoenix-marzban** [comment]
بنظر من ایده جالبی نیست همین که تنظیم کنیم اشتراکتون تموم شه بنظرم خیلی خوب هست الان تقریبا همه یه فیلترشکن رایگان یا پروکسی دارن تلگرامشون

**Comment by erfjab** [comment]
سلام وقت بخیر ، این مسئله یکم داستان داره و هنوز به این مراحل مونده ، فعلا برای توسعه ی نوتیس ، جداسازی پیام های کاربرهای expired و disable و limited هست ، در اینده به این موضوعات هم میرسیم
