### ISSUE TITLE
دستور حذف ربات !

### ISSUE THREAD

**Issue by Amirnikoo66** [erfjab/holderbot#59]
سلام 
ممنون از ربات خوبی ک ساختین
چون میخوام ربات رو از سرور مستر خارج کنم ، روش حذف ربات نصب شده ، رو میفرمایید

**Comment by erfjab** [comment]
سلام وقت بخیر ، بات رو دوباره ران کنید و هنگام درخواست اطلاعات ctrl + c بزنید
دستورحذف به زودی اضافه میشه
