### ISSUE TITLE
Generate Subscription QR Only

### ISSUE THREAD

**Issue by iamtheted** [erfjab/holderbot#6]
سلام عرفان عزیز

توی بات رسمی خود مرزبان وقتی روی QR بزنیم همه کانفیگ ها و در نهایت لینک سابسکریپشن رو جنریت میکنه 
و خب اگر کسی فقط QR لینک ساب و بخواد باید صبر کنه همه QR ها جنریت شه تهش اونو بفرسته
اگر بشه که ما انتخاب کنیم فقط QR لینک ساب جنریت شه خیلی خوبه 

مرسی ، ممنون بابت زحماتت

**Comment by erfjab** [comment]
سلام تد عزیز
در هولدربات با وارد کردن اسم یا لینک ساب می‌تونیم آمار کاربر رو دریافت کنیم که در این قسمت برای حل مشکل مرزبان ، می‌توان گزینه‌ی ایجاد QR لینک ساب هم اضافه کرد.

یعنی اسم کاربر را وارد کنیم، گزینه‌ی بارکد لینک ساب بزنیم و Q‌R دریافت کنیم. نظرسنجی میکنم حتما اضافه میکنم. ممنون از پیشنهادتون

**Comment by erfjab** [comment]
به نسخه‌ی 4 هولدربات اضافه شد✅
فعلا ریلیز نشده در آینده نزدیک ریلیز خواهد شد.
