### ISSUE TITLE
مشکل در فایل نصب

### ISSUE THREAD

**Issue by ehssanehs** [erfjab/holderbot#60]
چند بار اقدام به نصب کردم و هر دفعه با خطا روبرو شدم.
پس از بررسی فایل holderbot.sh متوجه شدم در انتهای فایل موقع وارد کردن مقادیر chatid و token در جدول bot از " استفاده شده است و باید با ' جایگزین شود.
سپاس از زحمات شما

**Comment by erfjab** [comment]
سلام وقت بخیر ، فیکس شد. تست کنید اطلاع بدید

**Comment by ehssanehs** [comment]
ممنون درست شد
