### ISSUE TITLE
آپدیت نشدن  Notice

### ISSUE THREAD

**Issue by ebikaargar** [erfjab/holderbot#63]
درود 

من بعد از نصب هولدر بات و فعال کردن  Notice تمای یوزرهایی که تاریخ یا حجمشون تموم شده بود آپدیت شدن

اما بعد از اون هر اشتراکی که غیرفعال میشه یا حجمش تموم میشه رو بروز نمیکنه تا بهشون اینباند holder رو بده

**Comment by erfjab** [comment]
> درود 
> 
> من بعد از نصب هولدر بات و فعال کردن  Notice تمای یوزرهایی که تاریخ یا حجمشون تموم شده بود آپدیت شدن
> 
> اما بعد از اون هر اشتراکی که غیرفعال میشه یا حجمش تموم میشه رو بروز نمیکنه تا بهشون اینباند holder رو بده 

لطفا بات رو از اول ران کنید و Change status بزنید
