### ISSUE TITLE
دوباره قعال نشدن Notice

### ISSUE THREAD

**Issue by Ashaxer** [erfjab/holderbot#64]
ربات اینباند Holderbot رو برای یوزر هایی که لیمیت شدن رو میفرسته اما موقع دوباره فعال شدن نمیاد به حالت اول برگردونه.
- مثلا یوزر حجم Daily براش تنظیم شده و بعد از فعال ریست شدن حجمش همچنان اینباند هاش قطعه.
- یا مثلا یه یوزر حجمش تموم میشه دستی ویرایش میکنیم و حجم یا زمان بهش میدیم اما همچنان اینباند فقط Holderbot میاد.

**Comment by erfjab** [comment]
> ربات اینباند Holderbot رو برای یوزر هایی که لیمیت شدن رو میفرسته اما موقع دوباره فعال شدن نمیاد به حالت اول برگردونه.
> - مثلا یوزر حجم Daily براش تنظیم شده و بعد از فعال ریست شدن حجمش همچنان اینباند هاش قطعه.
> - یا مثلا یه یوزر حجمش تموم میشه دستی ویرایش میکنیم و حجم یا زمان بهش میدیم اما همچنان اینباند فقط Holderbot میاد.

عزیز باید دستی فعال شه ، اینباند توسط بات فعال نمیشه.

**Comment by Ashaxer** [comment]
یوزری که خودکار تایمش ریست میشه چطور؟ اون که باید فعال شه؟
