### ISSUE TITLE
روش فعال سازی ربات تلگرام برای ادمین ها

### ISSUE THREAD

**Issue by MrOtto94** [erfjab/holderbot#71]
باسلام
لطفا روش فعال سازی ربات تلگرام برای ادمین ها رو توضیح بدید

**Comment by erfjab** [comment]
سلام وقت بخیر
در نسخه‌ی حاضر ادمین ها پشتیبانی نمی‌شوند. در نسخه‌ی 5 پشتیبانی خواهند شد.
