### ISSUE TITLE
اضافه کردن ادمین به ربات تلگرام

### ISSUE THREAD

**Issue by TIR3D4** [erfjab/holderbot#72]
سلام در ابتدا مچکرم بابت این پروژه فوق العاده 

مشکلم این هست که نمیدونم چطور میتونم برای ربات تلگرام ادمین های دیگه ای تنظیم کنم که اکانت های دیگه هم دسترسی داشته باشند لطفا اگر در فایل های سرور هم این کار امکان پذیر هست راهنمایی کنید.

**Comment by erfjab** [comment]
سلام وقت بخیر، سپاس از لطف‌تون.
بات برای این موضوع بهینه نشده و مناسب تک ادمینی میباشد اما یه روش جانبی هست که در کانال تلگرام @ErfJabs امروز منتشر خواهم شد. می‌توانید از آن فایل استقاده کنید.
