### ISSUE TITLE
پینشهاد(اضاف کردن ادمین های بیشتر)

### ISSUE THREAD

**Issue by jsmohssen** [erfjab/holderbot#8]
ممنون بابت بات خیلی خوبتون عرفان عزیز

لطفا امکان اضاف کردن ادمین های بیتشر رو هم به بات اضاف کنید..

**Comment by erfjab** [comment]
سلام وقت بخیر
ممنونم لطف دارید ، این اپشن در لیست آپدیت بعدی هست. حتما بهش توجه میشه.
