### ISSUE TITLE
تفاوت لینک subscription در ربات و پنل

### ISSUE THREAD

**Issue by amirooo70** [erfjab/holderbot#81]
درود. لینک subscription که در ربات تولید می‌شه با لینکی که در پنل تولید میشه متفاوته. منظورم قطعا دامنه یا زیردامنه نیست، بلکه ادامه آدرس subscription متفاوت هست. هر دو آدرس تولید شده هم کارآمد هستند. آیا این مساله یک خطا هست؟

**Comment by amirooo70** [comment]
با مثال زیر منظورم رو می‌رسونم:
Panel: sub.domain.com/sub/HzE1LYU3NjE2NTkzNDI2WX3wq-cmm
Bot: sub.domain.com/sub/HzE1LYU3NjE1ODQzNDgKjeVQn1RhS

**Comment by erfjab** [comment]
> با مثال زیر منظورم رو می‌رسونم:
> Panel: sub.domain.com/sub/HzE1LYU3NjE2NTkzNDI2WX3wq-cmm
> Bot: sub.domain.com/sub/HzE1LYU3NjE1ODQzNDgKjeVQn1RhS
> 
> آدرس‌ها تا یک جایی یکسان هستن و از یک جایی به بعد متفاوت می‌شوند

اها، هربار ساب جنریت میشه توکنش متفاوت میشه. چیز خاصی نیست.
