### ISSUE TITLE
نسخه نصب

### ISSUE THREAD

**Issue by hayousef68** [erfjab/holderbot#82]
سلام .ادمین جان ایشالاه کی قرار میدین دوباره .اومدم نصب کنم رو سرور جدیدم دیدم کلا پاکش کردین

**Comment by erfjab** [comment]
> سلام .ادمین جان ایشالاه کی قرار میدین دوباره .اومدم نصب کنم رو سرور جدیدم دیدم کلا پاکش کردین

درود، به زودی منتشر خواهد شد.
