### ISSUE TITLE
یک سری باگ ها بات داره و اکثر گزینه های معرفی شده کار نمیکنه، مثلا گزینه /cr Holder 1 5 100 30 دستور رو که اجرا می‌کنیم سریعا خطای زیر را نمیاش میده

### ISSUE THREAD

**Issue by jsmohssen** [erfjab/holderbot#9]
![image](https://github.com/erfjab/holderbot/assets/118536893/e1ed9cec-73b6-491b-a586-69081f512fe2)
یا دستور های دیگه مثل
/users
![image](https://github.com/erfjab/holderbot/assets/118536893/cd92c29d-a6b9-4fdb-ab1a-87c52824f507)

ویا دستور آمار کاربر به لینک ساب یا نام کاربر ری اکشنی نشون نمیده و خطا میده

**Comment by erfjab** [comment]
سلام وقت بخیر
این ارور در حال بررسی میباشد، سعی می‌کنیم تا آخر شب رفع کنیم. در چنل هولدربات اطلاع رسانی خواهد شد.

**Comment by erfjab** [comment]
عزیز باگ ها حل شدن ، هم اکنون میتوانید بات رو آپدیت کنید.
